### ISSUE TITLE
Ideas for --no-push and --no-sync 

### ISSUE THREAD

**Issue by ana** [edf-hpc/clara#102]
I've checking the latest changes pushed for the plugins repo and images:  the `--no-push` and `--no-sync` options. Given that the changes are not yet released i have a request for further improvement.

The  changes break current behavior  in setups where the new push or sync functionalities are not used/needed, it'll require to add the `--no-sync` or  `--no-push`. I'd like to suggest that when the parameters needed for the option sync or push are not present, clara defaults to the old behavior like if  `--no-sync` or  `--no-push` have been passed.

A second possibility, is making the code to do the opposite and add instead the options `--sync` and `--push`

Finally, another possibility that I think it's the best is not touching the command line parameters at all and handle this via the config.ini file. The goal is to use always the same command in all installations and not to make the user to think if in the current server they need to push/sync or not.

**Comment by mehdid** [comment]
IIRC, those features are only enabled if configuration file has some specific parameters. If one upgrades to new clara without changing its configuration file, it should not be bothered by those new CLI flags.

More specifically, those flags have an effect only when sftp_mode is enabled or push_cmd is configured. When they are missing, clara defaults to the old behavior. If it is not the case, it must be considered as a bug.

Otherwise, I do not see why we should not touch to the CLI flags. *shrug*
