### ISSUE TITLE
Avoid warnings when parallel param is not set

### ISSUE THREAD

**Issue by rezib** [edf-hpc/clara#60]
When the parallel parameter is not set in config file, clara warns those 2 messages:

```
# clara ipmi status pocn[270-272]
clara - Value 'parallel' not found in the section 'ipmi'
clara - parallel hasn't been set in config.ini, using 1 as value
```

Maybe those messages don't arguably deserve to be _warnings_, do they? I vote for _debug_ as soon as it does not prevent clara ipmi from running, and 1 is a sane default for people that do not worry that much for the parallel feature.

I opened this issue instead of push commits because:
- You may disagree with me,
- It needs some new code in `get_from_config()` and I'm not sure how you would have done this?

**Comment by ana** [comment]
Hey. I agree with having a problem here, but I see a different problem :)
 I find that adding the parallel parameter in the config file was a bad idea, the default should be 1, having it hardcoded in the code instead of just having the value 1 in the config file and when a user wants paralelism, then they should use --p=<level> . What do you think?
